##
# source directory
##
SRC_DIR := idea

##
# output directory

##
OUT_DIR := out

##
# sources
##
SOURCES := $(wildcard $(SRC_DIR)/*.java)

##
# classes
##
CLASSES := $(SOURCES:$(SRC_DIR)/%.java=$(OUT_DIR)/%.class)

##
# compiler and compiler flags
##
JC := javac
JCFLAGS := -d $(OUT_DIR)/ -cp $(SRC_DIR)/

##
# suffixes
##
.SUFFIXES: .java

##
# targets that do not produce output files
##
.PHONY: all clean

##
# default target(s)
##
all: $(CLASSES)

$(CLASSES): $(OUT_DIR)/%.class: $(SRC_DIR)/%.java
	$(JC) $(JCFLAGS) $<

##
# clean up any output files
##
clean:
	rm $(OUT_DIR)/*.class